(()=>{
 const form=document.getElementById('quote-form'); if(!form)return;
 const steps=[...form.querySelectorAll('.wizard-step')], next=document.getElementById('next'), back=document.getElementById('back'), submit=document.getElementById('submit'), fill=document.getElementById('progress-fill'), label=document.getElementById('step-label'); let step=1;
 const lang=()=>document.body.classList.contains('lang-es')?'es':'en';
 const detailMap={maintenance:[['general-cleanup','General cleanup / Limpieza general'],['routine-care','Routine care / Cuidado regular'],['seasonal','Seasonal work / Trabajo de temporada'],['overgrown','Overgrown area / Área crecida'],['not-sure','Not sure / No estoy seguro']],irrigation:[['leak','Leak / Fuga'],['broken-head','Broken sprinkler head / Aspersor roto'],['no-water','Area not receiving water / Área sin agua'],['controller','Controller or timer / Temporizador'],['wont-start','System will not turn on / No enciende'],['uneven','Uneven watering / Riego disparejo'],['not-sure','Not sure / No estoy seguro']],lawn:[['existing','Existing lawn problem / Problema de césped'],['bare','Bare area / Área sin pasto'],['damaged','Damaged area / Área dañada'],['new-project','New lawn project / Proyecto nuevo'],['not-sure','Not sure / No estoy seguro']],planting:[['roses','Roses / Rosas'],['flowers','Flowers or bed / Flores o jardinera'],['new-planting','New planting / Nueva plantación'],['plant-health','Plant care / Cuidado de plantas'],['not-sure','Not sure / No estoy seguro']],trimming:[['pruning','Pruning / Poda'],['shaping','Shaping / Formación'],['cleanup','Plant cleanup / Limpieza de plantas'],['not-sure','Not sure / No estoy seguro']],other:[['improvement','Outdoor improvement / Mejora exterior'],['other','Other / Otro'],['not-sure','Not sure / No estoy seguro']],unsure:[['not-sure','Not sure / No estoy seguro']]};
 function selectedService(){return form.querySelector('input[name=service]:checked')?.value||''}
 function syncDetails(){const s=selectedService(), sel=document.getElementById('service_detail'); if(!sel)return; sel.innerHTML='<option value="">Select / Seleccione</option>'+((detailMap[s]||detailMap.unsure).map(([v,t])=>`<option value="${v}">${t}</option>`).join(''));}
 form.querySelectorAll('input[name=service]').forEach(r=>r.addEventListener('change',syncDetails));
 const qp=new URLSearchParams(location.search).get('service');if(qp){const r=form.querySelector(`input[name=service][value="${CSS.escape(qp)}"]`);if(r){r.checked=true;syncDetails();}}
 function show(){steps.forEach(s=>s.hidden=Number(s.dataset.step)!==step);fill.style.width=(step/5*100)+'%';label.textContent=(lang()==='es'?`Paso ${step} de 5`:`Step ${step} of 5`);back.hidden=step===1;next.hidden=step===5;submit.hidden=step!==5;if(step===5)buildReview();}
 function validateCurrent(){const sec=steps[step-1];const fields=[...sec.querySelectorAll('[required]')];for(const f of fields){if(!f.checkValidity()){f.reportValidity();return false}}if(step===1&&!selectedService()){const first=form.querySelector('input[name=service]');first?.focus();return false}if(step===3&&!validateFiles())return false;return true}
 function validateFiles(){const inputs=['photo_wide','photo_close','photo_extra'].map(id=>document.getElementById(id));let total=0;const allowed=['image/jpeg','image/png','image/webp'];for(const input of inputs){const file=input.files?.[0];if(file){total+=file.size;if(!allowed.includes(file.type)){showFileError(lang()==='es'?'Use JPG, PNG o WebP solamente.':'Use JPG, PNG, or WebP images only.');return false}}}if(total>7*1024*1024){showFileError(lang()==='es'?'Las fotos juntas deben pesar menos de 7 MB.':'Combined photo size must stay under 7 MB.');return false}showFileError('');return true}
 function showFileError(msg){const el=document.getElementById('file-error');el.hidden=!msg;el.textContent=msg}
 next.addEventListener('click',()=>{if(!validateCurrent())return;if(step===1)syncDetails();step=Math.min(5,step+1);show();window.scrollTo({top:form.offsetTop-90,behavior:'smooth'})});back.addEventListener('click',()=>{step=Math.max(1,step-1);show();window.scrollTo({top:form.offsetTop-90,behavior:'smooth'})});
 function txt(id){const el=document.getElementById(id);return el?.selectedOptions?.[0]?.textContent?.trim()||el?.value?.trim()||''}
 function fileCount(){return ['photo_wide','photo_close','photo_extra'].reduce((n,id)=>n+(document.getElementById(id)?.files?.length?1:0),0)}
 function buildReview(){const s=selectedService();const serviceLabel=form.querySelector(`label[for="s-${s}"] span[data-lang="${lang()}"]`)?.textContent||s;const rows=[[lang()==='es'?'Servicio':'Service',serviceLabel],[lang()==='es'?'Detalle':'Detail',txt('service_detail')||'—'],[lang()==='es'?'Ciudad / ZIP':'City / ZIP',`${txt('city')} ${txt('zip')}`.trim()],[lang()==='es'?'Fotos':'Photos',String(fileCount())],[lang()==='es'?'Contacto':'Contact',`${txt('name')} · ${txt('contact_preference')}`]];document.getElementById('review').innerHTML=rows.map(([a,b])=>`<div class="review-row"><strong>${escapeHtml(a)}</strong><span>${escapeHtml(b)}</span></div>`).join('');const ready=document.getElementById('readiness');if(fileCount()===0){ready.classList.add('warn');ready.textContent=lang()==='es'?'La solicitud está lista, pero una foto puede ayudar a Ramiro a entender el proyecto más rápido.':'Your request is ready, but a photo may help Ramiro understand the project faster.'}else{ready.classList.remove('warn');ready.textContent=lang()==='es'?'Todo se ve listo para revisión.':'Everything looks ready for review.'}}
 function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function ref(){return 'JDR-'+new Date().toISOString().slice(2,10).replaceAll('-','')+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}
 form.addEventListener('submit',e=>{if(!validateCurrent()){e.preventDefault();return}const r=ref();document.getElementById('reference').value=r;const s=selectedService();const summary=[`Reference: ${r}`,`Service: ${s}`,`Detail: ${txt('service_detail')}`,`City/ZIP: ${txt('city')} ${txt('zip')}`,`Timing: ${txt('timing')}`,`Preferred contact: ${txt('contact_preference')}`,`Preferred language: ${lang()==='es'?'Español':'English'}`,`Photos attached: ${fileCount()}`].join(' | ');document.getElementById('lead_summary').value=summary;form.querySelector('input[name=language]').value=lang();try{sessionStorage.setItem('ramiro-last-request',JSON.stringify({reference:r,service:s,contact:txt('contact_preference'),lang:lang()}))}catch(err){}});
 document.addEventListener('ramiro:language',show);show();
})();